### ISSUE TITLE
One question: How often the Update() runs?

### ISSUE THREAD

**Issue by n00el** [SH42913/gunshotwound#1]
Hello! 

First of all, thanks for release this code!

But I have one question, what I can't find out.

Then Update() function runs every tick? Or every 1000 - so every secounds?

**Comment by SH42913** [comment]
Yeah, my script call Update() every game tick. For GSW1 Update() is very complicated and it's hard impact on performance. It's very bad solution.
This code is very raw and outdated, you'd better to checkout sources of [GSW2](https://github.com/SH42913/GunshotWound2) or even pre-alpha of [GSW3](https://github.com/SH42913/gsw2rh).

**Comment by n00el** [comment]
Thank! :) Yeah, I know! Keep up the good work, sir.

**Comment by n00el** [comment]
I want to create something similar, a "realistic" damage system in FiveM, and do some research. The base of this mod, and the features are very intresting!
For FiveM a script what run every tick, with this mutch code, even more perforcmance killer :D

**Comment by SH42913** [comment]
Wow, dude, if you know how FiveM work, can we collaborate and port GSW3 to FiveM? GSW3 is enough optimized.
Do you have Discord?

**Comment by n00el** [comment]
Just my tiny private server, but I am more than happy if I can help you :)
https://discord.gg/KtAUtXn
